apiVersion: v1
kind: Service
metadata:
  name: ${cluster-name}-lb
  labels:
    app: ${app-label}
spec:
  selector:
    app: ${app-label}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
